In [7]:
import pandas as pd
import numpy as np

In [2]:
nfl_data = pd.read_csv("NFLPlaybyPlay.csv")

/Users/akashponugoti/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (42,166,167,168,169,174,175,178,179,182,183,188,189,190,191,194,195,203,204,205,218,219,220,231,232,233,238,240,241,249) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
nfl_data.head()

,play_id,game_id,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,...,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv
0,46,2009091000,PIT,TEN,PIT,home,TEN,TEN,30.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
1,68,2009091000,PIT,TEN,PIT,home,TEN,PIT,58.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
2,92,2009091000,PIT,TEN,PIT,home,TEN,PIT,53.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
3,113,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
4,139,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0

In [4]:
missing_vals = nfl_data.isnull().sum()
missing_vals[0:20]

play_id                          0
game_id                          0
home_team                        0
away_team                        0
posteam                      13242
posteam_type                 12879
defteam                      12879
side_of_field                  600
yardline_100                 13070
game_date                        0
quarter_seconds_remaining      141
half_seconds_remaining         165
game_seconds_remaining         163
game_half                        0
quarter_end                      0
drive                            0
sp                               0
qtr                              0
down                         67962
goal_to_go                   12707
dtype: int64

In [8]:
total_cells = np.product(nfl_data.shape)
total_cells

114589605

In [9]:
nfl_data.shape

(449371, 255)

In [12]:
total_missing = missing_vals.sum()
total_missing

44121484

In [10]:
449371*255

114589605

In [13]:
percent_missing = (total_missing / total_cells) * 100 
percent_missing

38.50391490571942

In [15]:
nfl_data.dropna()

Empty DataFrame
Columns: [play_id, game_id, home_team, away_team, posteam, posteam_type, defteam, side_of_field, yardline_100, game_date, quarter_seconds_remaining, half_seconds_remaining, game_seconds_remaining, game_half, quarter_end, drive, sp, qtr, down, goal_to_go, time, yrdln, ydstogo, ydsnet, desc, play_type, yards_gained, shotgun, no_huddle, qb_dropback, qb_kneel, qb_spike, qb_scramble, pass_length, pass_location, air_yards, yards_after_catch, run_location, run_gap, field_goal_result, kick_distance, extra_point_result, two_point_conv_result, home_timeouts_remaining, away_timeouts_remaining, timeout, timeout_team, td_team, posteam_timeouts_remaining, defteam_timeouts_remaining, total_home_score, total_away_score, posteam_score, defteam_score, score_differential, posteam_score_post, defteam_score_post, score_differential_post, no_score_prob, opp_fg_prob, opp_safety_prob, opp_td_prob, fg_prob, safety_prob, td_prob, extra_point_prob, two_point_conversion_prob, ep, epa, total_home_epa, total_away_epa, total_home_rush_epa, total_away_rush_epa, total_home_pass_epa, total_away_pass_epa, air_epa, yac_epa, comp_air_epa, comp_yac_epa, total_home_comp_air_epa, total_away_comp_air_epa, total_home_comp_yac_epa, total_away_comp_yac_epa, total_home_raw_air_epa, total_away_raw_air_epa, total_home_raw_yac_epa, total_away_raw_yac_epa, wp, def_wp, home_wp, away_wp, wpa, home_wp_post, away_wp_post, total_home_rush_wpa, total_away_rush_wpa, total_home_pass_wpa, total_away_pass_wpa, air_wpa, yac_wpa, ...]
Index: []

[0 rows x 255 columns]

In [16]:
cols_with_NaN_dropped = nfl_data.dropna(axis=1)
cols_with_NaN_dropped.head()

,play_id,game_id,home_team,away_team,game_date,game_half,quarter_end,drive,sp,qtr,...,total_away_pass_wpa,total_home_comp_air_wpa,total_away_comp_air_wpa,total_home_comp_yac_wpa,total_away_comp_yac_wpa,total_home_raw_air_wpa,total_away_raw_air_wpa,total_home_raw_yac_wpa,total_away_raw_yac_wpa,replay_or_challenge
0,46,2009091000,PIT,TEN,2009-09-10,Half1,0,1,0,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
1,68,2009091000,PIT,TEN,2009-09-10,Half1,0,1,0,1,...,-0.004655,-0.028383,0.028383,0.033038,-0.033038,-0.028383,0.028383,0.033038,-0.033038,0
2,92,2009091000,PIT,TEN,2009-09-10,Half1,0,1,0,1,...,-0.004655,-0.028383,0.028383,0.033038,-0.033038,-0.028383,0.028383,0.033038,-0.033038,0
3,113,2009091000,PIT,TEN,2009-09-10,Half1,0,1,0,1,...,0.044921,-0.028383,0.028383,0.033038,-0.033038,0.081542,-0.081542,-0.126463,0.126463,0
4,139,2009091000,PIT,TEN,2009-09-10,Half1,0,1,0,1,...,0.044921,-0.028383,0.028383,0.033038,-0.033038,0.081542,-0.081542,-0.126463,0.126463,0